import environ

API_KEY = environ['API_KEY']
API_SCRET = environ['API_SCRET']
BEARER_TOKEN = environ['BEARER_TOKEN']
#ACCESS_TOKEN = environ['ACCESS_TOKEN']
#ACCESS_TOKEN_SECRET = environ['ACCESS_TOKEN_SECRET']
ACCESS_TOKEN = environ['ACCESS_TOKEN']
ACCESS_TOKEN_SECRET = environ['ACCESS_TOKEN_SECRET']